name: mood_repository
description: A Dart Repository which manages the mood domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  amplify_datastore: ^1.2.0
  amplify_flutter: ^1.2.0
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.2
  test: ^1.16.4
  very_good_analysis: ^5.0.0+1
