name: user_profile_repository
description: A Dart Repository which manages user data.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

dependencies:
  amplify_auth_cognito: ^1.2.0
  amplify_flutter: ^1.2.0
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.1
  test: ^1.16.4
  very_good_analysis: ^5.0.0+1